export const themes = {
    greyscale: {
        background: "#333333",
        text: "#ffffff",
        secondary_text: "#ffffff",
        drawer_background: "#49494C",
        bg_list_Item_Icon: "#333333",
        bg_arrow: "#26272B",
        bg_arrow_hover: "#3A3B40",
        tabs_bg: "#26272B",
        tabs_notselected_color: "#aaa",
        cross_color: "#aaa",
        cross_color_hover: "rgba(255, 255, 255, 0.1)",
        dialog_search_icon: "#BCB6B6",
        box_bg: "#49494C",
        bg_behind_boxes: "#333333",
        box_head: "#6E6E6D",
        right_sidebar_border: "#3a3a3a",
        scroll_1 : "#fff",
        scroll_2 : "#666",
        filter_input_bg: "#26272B",
        filter_input_bg_focused: "black",
        table_head_bg: "#444444"
    },
    light: {
        background: "#ECF9FF",
        text: "#0B4259",
        secondary_text: "#ffffff",
        drawer_background: "#0B4259",
        bg_list_Item_Icon: "#3E88AD",
        bg_arrow: "#3E88AD",
        bg_arrow_hover: "#0B4259",
        tabs_bg: "#0B4259",
        tabs_notselected_color: "#fff",
        cross_color: "#0B4259",
        cross_color_hover: "#B7E0F4",
        dialog_search_icon: "#ffffff",
        box_bg: "#3E88AD",
        bg_behind_boxes: "#B7E0F4",
        box_head: "#0B4259",
        right_sidebar_border: "#0B4259",
        scroll_1 : "#B7E0F4",
        scroll_2 : "#0B4259",
        filter_input_bg: "#ffffff",
        filter_input_bg_focused: "#ffffff",
        table_head_bg: "#0B4259"
    },
    // hacker: {
    //     background: "#0f0f0f",
    //     text: "#00ff00",
    // },
};
