export const themes = {
    dark: {
        background: "#333333",
        hero_border: "#333333",
        text: "#ffffff",
        secondary_text: "#ffffff",
        drawer_background: "#49494C",
        bg_list_Item_Icon: "#333333",
        bg_table_cell: "#333333",
        bg_arrow: "#26272B",
        bg_arrow_hover: "#3A3B40",
        tabs_bg: "#26272B",
        tabs_notselected_color: "#aaa",
        cross_color: "#aaa",
        cross_color_hover: "rgba(255, 255, 255, 0.1)",
        dialog_search_icon: "#BCB6B6",
        box_bg: "#49494C",
        bg_behind_boxes: "#333333",
        bg_behind_boxes_2: "#49494C",
        bg_behind_boxes_2_border: "#49494C",
        box_head: "#6E6E6D",
        right_sidebar_border: "#3a3a3a",
        scroll_1 : "#fff",
        scroll_2 : "#666",
        filter_input_bg: "#26272B",
        filter_input_bg_border: "#26272B",
        filter_input_bg_focused: "black",
        table_head_bg: "#444444",
        box_info_color: "#b5b5b5",
        button: "#333333",
        button_hover: "#000000",
        text_2 : "#D9D9D9",
        input_bg: "#000000",
        login_button_bg_hover: "#2E2E30",
        login_button_bg_border: "#ffffff",
        right_grid_bg: "#000000",
        right_grid_bg_border: "#000000",
        tagline_hero_section: "#EFEFEF",
        get_started_button_hover: "#b5b5b5",
        border_navbar_buttons: "#EFEFEF",
        drawer_lists_text_color: "#b5b5b5",
        landingPage_drawer_bg: "#000000",
        desc_text: "#EFEFEF",
        box_bg_2: "#26272B",
        box_bg_2_border: "#26272B",
        bg_contactus: "#b5b5b5",
        drawer_background_border: "#49494C",
        text_3 : "#ffffff",
        dialog_border: "#BCB6B6",
        box_bg_border: "#49494C",
        bg_behind_boxes_border: "#49494C",
        ChatBot_bg: "#1e1e1e",
        ChatBot_IconButton: "#2e2e2e",
        ChatBot_IconButton_bg: "#aaaaaa",
        ChatBot_text: "#ffffff",
        ChatBot_message_bg: "#cccccc",
        ChatBot_message_text: "#000000",
        ChatBot_response_bg: "#333333",
        ChatBot_response_text: "#ffffff",
        ChatBot_border: "#333333",
        ChatBot_input_bg: "#333333",
        ChatBot_IconButton_msgIcon: "#333333",
        ChatBot_IconButton_bg_Hover: "#cccccc",
        ChatBot_Ask_Anything: "#aaaaaa",
    },
    light: {
        background: "#ECF9FF",
        hero_border: "#ECF9FF",
        text: "#0B4259",
        secondary_text: "#ffffff",
        drawer_background: "#0B4259",
        bg_list_Item_Icon: "#3E88AD",
        bg_table_cell: "#3E88AD",
        bg_arrow: "#3E88AD",
        bg_arrow_hover: "#0B4259",
        tabs_bg: "#0B4259",
        tabs_notselected_color: "#fff",
        cross_color: "#0B4259",
        cross_color_hover: "#B7E0F4",
        dialog_search_icon: "#ffffff",
        box_bg: "#3E88AD",
        bg_behind_boxes: "#B7E0F4",
        bg_behind_boxes_2: "#B7E0F4",
        bg_behind_boxes_2_border: "#B7E0F4",
        box_head: "#0B4259",
        right_sidebar_border: "#0B4259",
        scroll_1 : "#B7E0F4",
        scroll_2 : "#0B4259",
        filter_input_bg: "#ffffff",
        filter_input_bg_border: "#ffffff",
        filter_input_bg_focused: "#ffffff",
        table_head_bg: "#0B4259",
        box_info_color: "#ECF9FF",
        button: "#0B4259",
        button_hover: "#3E88AD",
        text_2 : "#0B4259",
        input_bg: "#ffffff",
        login_button_bg_hover: "#0B4259",
        login_button_bg_border: "#3E88AD",
        right_grid_bg: "#0B4259",
        right_grid_bg_border: "#0B4259",
        tagline_hero_section: "#ffffff",
        get_started_button_hover: "#3E88AD",
        border_navbar_buttons: "#ECF9FF",
        drawer_lists_text_color: "#0B4259",
        landingPage_drawer_bg: "#3E88AD",
        desc_text: "#0B4259",
        box_bg_2: "#3E88AD",
        box_bg_2_border: "#3E88AD",
        bg_contactus: "#B7E0F4",
        drawer_background_border: "#0B4259",
        text_3 : "#ffffff",
        dialog_border: "#BCB6B6",
        box_bg_border: "#3E88AD",
        bg_behind_boxes_border: "#B7E0F4",
        ChatBot_bg: "#0B4259",
        ChatBot_IconButton: "#3E88AD",
        ChatBot_IconButton_bg: "#3E88AD",
        ChatBot_text: "#ffffff",
        ChatBot_message_bg: "#3E88AD",
        ChatBot_message_text: "#ffffff",
        ChatBot_response_bg: "#B7E0F4",
        ChatBot_response_text: "#000000",
        ChatBot_border: "#B7E0F4",
        ChatBot_input_bg: "#333333",
        ChatBot_IconButton_msgIcon: "#0B4259",
        ChatBot_IconButton_bg_Hover: "#3E88AD",
        ChatBot_Ask_Anything: "#B7E0F4",
    },
    hacker: {
        background: "#000000",
        hero_border: "#75FA4C",
        text: "#75FA4C",
        secondary_text: "#75FA4C",
        drawer_background: "#000000",
        bg_list_Item_Icon: "#75FA4C",
        bg_table_cell: "#000000",
        bg_arrow: "#75FA4C",
        bg_arrow_hover: "#75FA4C",
        tabs_bg: "#000000",
        tabs_notselected_color: "#75FA4C",
        cross_color: "#75FA4C",
        cross_color_hover: "rgba(255, 255, 255, 0.1)",
        dialog_search_icon: "#75FA4C",
        box_bg: "#000000",
        bg_behind_boxes: "#000000",
        bg_behind_boxes_2: "#000000",
        bg_behind_boxes_2_border: "#75FA4C",
        box_head: "#75FA4C",
        right_sidebar_border: "#75FA4C",
        scroll_1 : "#75FA4C",
        scroll_2 : "#ECFFDC",
        filter_input_bg: "#000000",
        filter_input_bg_border: "#75FA4C",
        filter_input_bg_focused: "black",
        table_head_bg: "#75FA4C",
        box_info_color: "#75FA4C",
        button: "#000000",
        button_hover: "#000000",
        text_2 : "#75FA4C",
        input_bg: "#000000",
        login_button_bg_hover: "#000000",
        login_button_bg_border: "#75FA4C",
        right_grid_bg: "#000000",
        right_grid_bg_border: "#75FA4C",
        tagline_hero_section: "#EFEFEF",
        get_started_button_hover: "#75FA4C",
        border_navbar_buttons: "#75FA4C",
        drawer_lists_text_color: "#75FA4C",
        landingPage_drawer_bg: "#000000",
        desc_text: "#75FA4C",
        box_bg_2: "#000000",
        box_bg_2_border: "#75FA4C",
        bg_contactus: "#75FA4C",
        drawer_background_border: "#75FA4C",
        text_3 : "#000000",
        dialog_border: "#75FA4C",
        box_bg_border: "#75FA4C",
        bg_behind_boxes_border: "#75FA4C",
        ChatBot_bg: "#000000",
        ChatBot_IconButton: "#75FA4C",
        ChatBot_IconButton_bg: "#75FA4C",
        ChatBot_text: "#75FA4C",
        ChatBot_message_bg: "#75FA4C",
        ChatBot_message_text: "#000000",
        ChatBot_response_bg: "#75FA4C",
        ChatBot_response_text: "#000000",
        ChatBot_border: "#75FA4C",
        ChatBot_input_bg: "#75FA4C",
        ChatBot_IconButton_msgIcon: "#000000",
        ChatBot_IconButton_bg_Hover: "#75FA4C",
        ChatBot_Ask_Anything: "#75FA4C",
    },
};
